// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokePoke.Infrastructure.Persistence.Context;

#nullable disable

namespace PokePoke.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PokePoke.Core.Domain.Entities.Pokemonn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Pokemones", (string)null);
                });

            modelBuilder.Entity("PokePoke.Core.Domain.Entities.PokemonTipo", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("PokemonId", "TipoId");

                    b.HasIndex("TipoId");

                    b.ToTable("PokemonesTipos", (string)null);
                });

            modelBuilder.Entity("PokePoke.Core.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regiones", (string)null);
                });

            modelBuilder.Entity("PokePoke.Core.Domain.Entities.Tipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipos", (string)null);
                });

            modelBuilder.Entity("PokePoke.Core.Domain.Entities.Pokemonn", b =>
                {
                    b.HasOne("PokePoke.Core.Domain.Entities.Region", "Region")
                        .WithMany("Pokemones")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("PokePoke.Core.Domain.Entities.PokemonTipo", b =>
                {
                    b.HasOne("PokePoke.Core.Domain.Entities.Pokemonn", "Pokemon")
                        .WithMany("PokemonesTipos")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokePoke.Core.Domain.Entities.Tipo", "Tipo")
                        .WithMany("PokemonesTipos")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("PokePoke.Core.Domain.Entities.Pokemonn", b =>
                {
                    b.Navigation("PokemonesTipos");
                });

            modelBuilder.Entity("PokePoke.Core.Domain.Entities.Region", b =>
                {
                    b.Navigation("Pokemones");
                });

            modelBuilder.Entity("PokePoke.Core.Domain.Entities.Tipo", b =>
                {
                    b.Navigation("PokemonesTipos");
                });
#pragma warning restore 612, 618
        }
    }
}
